# Generated by Django 4.0.2 on 2022-02-26 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='resume/images')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('mobile', models.IntegerField()),
                ('experiace', models.TextField()),
                ('matrialStatus', models.CharField(max_length=255)),
                ('workplace', models.CharField(max_length=1000)),
                ('designation', models.CharField(max_length=500)),
                ('links', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('report', models.ImageField(upload_to='medical/images')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('height', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('bgroup', models.CharField(max_length=10)),
                ('problem', models.TextField()),
                ('doctor', models.CharField(max_length=1000)),
                ('history', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='contact/images')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('mobile', models.IntegerField()),
                ('matrialStatus', models.CharField(max_length=255)),
                ('workplace', models.CharField(max_length=1000)),
                ('designation', models.CharField(max_length=500)),
                ('links', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
