# Generated by Django 4.0.2 on 2022-02-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='medical',
            name='slug',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='slug',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
